CROSS_COMPILE =arm-linux-gnueabihf-gcc

BABY_MONITOR_INC_DIR = inc
BABY_MONITOR_LIB_INC_DIR = lib
BABY_MONITOR_VIDEO_DIR = video
BABY_MONITOR_WEB_DIR = web

BABY_BBG_INC_PATH = $(BABY_MONITOR_INC_DIR)/baby
BBG_HW_LIB_PATH = $(BABY_MONITOR_LIB_INC_DIR)/BBGHardware
BABY_MONITOR_SYS_LIB_PATH = $(BABY_MONITOR_LIB_INC_DIR)/sys
BABY_MONITOR_VIDEO_CAPTURE_SRC_FILE = $(wildcard $(BABY_MONITOR_VIDEO_DIR)/*.c)

BBG_HW_LIB_SRC_FILE = $(wildcard $(BBG_HW_LIB_PATH)/*.c)
BABY_BBG_SRC_FILE = $(wildcard *.c)
BABY_MONITOR_MICROPHONE_SRC_FILE = $(wildcard sound/*.c)
BABY_MONITOR_SYS_LIB_SRC_FILE = $(wildcard $(BABY_MONITOR_SYS_LIB_PATH)/*.c)

PARENT_BBG_INC_PATH = $(BABY_MONITOR_INC_DIR)/parent
PARENT_BBG_SRC_FILE = $(wildcard parent/*.c)

BABY_BBG_OBJ_FILE = babyMonitor
PARENT_BBG_OBJ_FILE = parentMonitor
BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE = captureVideo

NFS_PATH = $(HOME)/cmpt433/public/myApps
ASOUND_LIB_PATH = $(HOME)/cmpt433/public/asound_lib_BBB
V4L2_LIB_PATH = $(BABY_MONITOR_LIB_INC_DIR)/v4l2_lib
CFLAGS = -Wall -g -std=c99 -D _POSIX_C_SOURCE=200809L -Werror
IFLAGS_BABY = -I $(BABY_BBG_INC_PATH) -I $(BABY_MONITOR_SYS_LIB_PATH) -I $(BBG_HW_LIB_PATH)
IFLAGS_PARENT = -I $(BABY_BBG_INC_PATH) -I $(PARENT_BBG_INC_PATH) -I $(BABY_MONITOR_SYS_LIB_PATH) -I $(BBG_HW_LIB_PATH)
LFLAGS = -L$(ASOUND_LIB_PATH) -lasound -lpthread -lm
LFLAGS_VIDEO = -L$(V4L2_LIB_PATH) -lv4l2

# optional build flags
# DEBUG_MODE = -D DEBUG_MODE
DEMO_MODE = -D DEMO_MODE

all: begin baby parent captureVideo webServer done

begin:
	@echo "Start compling baby monitoring system..."
	@echo

baby:
	@echo "Start compling $(BABY_BBG_OBJ_FILE)"
	$(CROSS_COMPILE) $(CFLAGS) $(IFLAGS_BABY) $(BBG_HW_LIB_SRC_FILE) $(BABY_MONITOR_SYS_LIB_SRC_FILE) $(BABY_MONITOR_MICROPHONE_SRC_FILE) $(BABY_BBG_SRC_FILE) $(DEBUG_MODE) $(DEMO_MODE) -o $(BABY_BBG_OBJ_FILE) $(LFLAGS)
	cp $(BABY_BBG_OBJ_FILE) $(NFS_PATH)/
	@echo "Finish compling $(BABY_BBG_OBJ_FILE)"
	@echo

.PHONY: parent
parent:
	@echo "Start compling $(PARENT_BBG_OBJ_FILE)"
	$(CROSS_COMPILE) $(CFLAGS) $(IFLAGS_PARENT) $(BABY_MONITOR_SYS_LIB_SRC_FILE) $(PARENT_BBG_SRC_FILE) $(DEBUG_MODE) $(DEMO_MODE) -o $(PARENT_BBG_OBJ_FILE) $(LFLAGS)
	cp $(PARENT_BBG_OBJ_FILE) $(NFS_PATH)/
	@echo "Finish compling $(PARENT_BBG_OBJ_FILE)"
	@echo

captureVideo:
	@echo "Start compling $(BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE)"
	$(CROSS_COMPILE) $(CFLAGS) $(BABY_MONITOR_VIDEO_CAPTURE_SRC_FILE) -o $(BABY_MONITOR_VIDEO_DIR)/$(BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE) $(LFLAGS_VIDEO)
	mkdir -p $(NFS_PATH)/$(BABY_MONITOR_VIDEO_DIR)
	chmod 777 $(NFS_PATH)/$(BABY_MONITOR_VIDEO_DIR)
	cp $(BABY_MONITOR_VIDEO_DIR)/$(BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE) $(NFS_PATH)/$(BABY_MONITOR_VIDEO_DIR)/
	@echo "Finish compling $(BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE)"

webServer:
	mkdir -p $(NFS_PATH)/$(BABY_MONITOR_WEB_DIR)/
	cp -R $(BABY_MONITOR_WEB_DIR)/* $(NFS_PATH)/$(BABY_MONITOR_WEB_DIR)/

done:
	@echo "Finsh compling baby monitoring system!!!"
	@echo

clean:
	rm -f $(BABY_BBG_OBJ_FILE)
	rm -f $(PARENT_BBG_OBJ_FILE)
	rm -f $(BABY_MONITOR_VIDEO_DIR)/$(BABY_MONITOR_VIDEO_CAPTURE_OBJ_FILE)
	rm -f $(NFS_PATH)/$(BABY_BBG_OBJ_FILE)
	rm -f $(NFS_PATH)/$(PARENT_BBG_OBJ_FILE)
	rm -rf $(NFS_PATH)/$(BABY_MONITOR_VIDEO_DIR)
	rm -rf $(NFS_PATH)/$(BABY_MONITOR_WEB_DIR)

